### ISSUE TITLE
maven clean package does not work on win 10 , java 9

### ISSUE THREAD

**Issue by fornof** [jetty-project/embedded-jetty-jsp#14]
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on 
project embedded-jetty-jsp: There are test failures
Tests in error:
  JstlTest.canServeJspWithTaglib:33->resourceWithUrl:39 ▒ IO Server returned HTT...
...
INFO: Stopped scavenging
Feb 02, 2018 5:37:46 AM org.eclipse.jetty.server.handler.ContextHandler doStop
INFO: Stopped o.e.j.s.ServletContextHandler@4d14b6c2{/,file:///C:/web/files/embedded-jetty-jsp/target/classes/webroot/,UNAVAILABLE}
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.692 sec <<< FAILURE! - in org.eclipse.jetty.demo.JstlTest
canServeJspWithTaglib(org.eclipse.jetty.demo.JstlTest)  Time elapsed: 0.645 sec  <<< ERROR!
java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8080/test/jstl.jsp
        at org.eclipse.jetty.demo.JstlTest.resourceWithUrl(JstlTest.java:39)
        at org.eclipse.jetty.demo.JstlTest.canServeJspWithTaglib(JstlTest.java:33)
...
 Please refer to C:\web\files\embedded-jetty-jsp\target\surefire-reports for the individual test results.

[org.eclipse.jetty.demo.JstlTest.txt](https://github.com/jetty-project/embedded-jetty-jsp/files/1689191/org.eclipse.jetty.demo.JstlTest.txt)

[TEST-org.eclipse.jetty.demo.JstlTest.txt](https://github.com/jetty-project/embedded-jetty-jsp/files/1689192/TEST-org.eclipse.jetty.demo.JstlTest.txt)

**Comment by fornof** [comment]
I ended up moving my code to Java 8 as the solution.
